export default {
  CSS: "Cascading Style Sheet",
  GIF: "Graphic Interchange Format",
  HTML: "Hyper Text Markup Language",
  API: "Application Programming Interface",
  SPA: "Single Page Application",
  JSON: "JavaScript Object Notation",
  AWS: "Amazon Web Services",
  GCP: "Google Cloud Platform",
  REST: "Representational State Transfer",
  CDN: "Content Delivery Network",
  CRUD: "Create Read Update Delete",
  DOM: "Document Object Model",
  GUI: "Graphical User Interface",
  IDE: "Integrated Development Model",
  MVC: "Model View Controller",
  OOP: "Object Oriented Programming",
  CLI: "Command Line Interface",
  DNS: "Domain Name Server",
  FTP: "File Transfer Protocol",
  HTTP: "HyperText Transfer Protocol",
  VPN: "Virtual Private Network",
  WWW: "World Wide Web",
  SEO: "Search Engine Optimization",
  SQL: "Structured Query Language",
};
